export const GET_CONTACT_SUCCESS = '@GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAILED = '@GET_CONTACT_FAILED';

export const ADD_CONTACT_SUCCESS = '@ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILED = '@ADD_CONTACT_FAILED';

export const GET_DETAIL_CONTACT_SUCCESS = '@GET_DETAIL_CONTACT_SUCCESS';
export const GET_DETAIL_CONTACT_FAILED = '@GET_DETAIL_CONTACT_FAILED';

export const UPDATE_CONTACT_SUCCESS = '@UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILED = '@UPDATE_CONTACT_FAILED';

export const DELETE_CONTACT_SUCCESS = '@DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILED = '@DELETE_CONTACT_FAILED';

export const CONTACT_LOADING = '@CONTACT_LOADING';
